version: '3.7'

services:
  mini-project:
    build: .
    ports:
      - 8080:8080
    restart: on-failure
    networks:
      - my-network
    depends_on:
      - mariadb-services

  mariadb-services:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ./webapp:/opt/webapp
      - ./mariadb/schema.sql:/data/application/init.sql
    command: --init-file /data/application/init.sql
    networks:
      - my-network

networks:
  my-network:
    driver: bridge