version: '3.7'

services:
  mini-project:
    build: .
    ports:
      - 8080:8080
    restart: on-failure
    networks:
      - my-network
    depends_on:
      - mariadb-services

  mariadb-services:
    image: mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=password
      - MARIADB_DATABASE=mini_project
      - MARIADB_USER=root 
      - MARIADB_PASSWORD=password
    ports:
      - 3306:3306
    volumes:
      - /home/aji/mariadbvolume:/var/lib/mysql
      - ./mariadb/schema.sql:/data/application/init.sql
    command: --init-file /data/application/init.sql
    networks:
      - my-network

networks:
  my-network:
    driver: bridge