version: '3.7'

services:
  mini-project:
    build: .
    ports:
      - 8080:8080
    restart: on-failure
    networks:
      - my-network
    depends_on:
      - mysql-services

  mysql-services:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mini-project
      - MYSQL_PASSWORD=password
    ports:
      - 3306:3306
    volumes:
      - ./webapp:/opt/webapp
      - ./mariadb/schema.sql:/data/application/init.sql
    command: --init-file /data/application/init.sql
    networks:
      - my-network

networks:
  my-network:
    driver: bridge