// Code generated by mockery v2.14.1. DO NOT EDIT.

package mocks

import (
	teachers "mini-project/businesses/teachers"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// CreateTeacher provides a mock function with given fields: teacherDomain
func (_m *Repository) CreateTeacher(teacherDomain *teachers.Domain) teachers.Domain {
	ret := _m.Called(teacherDomain)

	var r0 teachers.Domain
	if rf, ok := ret.Get(0).(func(*teachers.Domain) teachers.Domain); ok {
		r0 = rf(teacherDomain)
	} else {
		r0 = ret.Get(0).(teachers.Domain)
	}

	return r0
}

// Delete provides a mock function with given fields: id
func (_m *Repository) Delete(id string) bool {
	ret := _m.Called(id)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// GetByEmail provides a mock function with given fields: studentDomain
func (_m *Repository) GetByEmail(studentDomain *teachers.Domain) teachers.Domain {
	ret := _m.Called(studentDomain)

	var r0 teachers.Domain
	if rf, ok := ret.Get(0).(func(*teachers.Domain) teachers.Domain); ok {
		r0 = rf(studentDomain)
	} else {
		r0 = ret.Get(0).(teachers.Domain)
	}

	return r0
}

// GetByID provides a mock function with given fields: id
func (_m *Repository) GetByID(id string) teachers.Domain {
	ret := _m.Called(id)

	var r0 teachers.Domain
	if rf, ok := ret.Get(0).(func(string) teachers.Domain); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(teachers.Domain)
	}

	return r0
}

// GetTeachers provides a mock function with given fields:
func (_m *Repository) GetTeachers() []teachers.Domain {
	ret := _m.Called()

	var r0 []teachers.Domain
	if rf, ok := ret.Get(0).(func() []teachers.Domain); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]teachers.Domain)
		}
	}

	return r0
}

// Update provides a mock function with given fields: id, blogDomain
func (_m *Repository) Update(id string, blogDomain *teachers.Domain) teachers.Domain {
	ret := _m.Called(id, blogDomain)

	var r0 teachers.Domain
	if rf, ok := ret.Get(0).(func(string, *teachers.Domain) teachers.Domain); ok {
		r0 = rf(id, blogDomain)
	} else {
		r0 = ret.Get(0).(teachers.Domain)
	}

	return r0
}

type mockConstructorTestingTNewRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepository(t mockConstructorTestingTNewRepository) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
