// Code generated by mockery v2.14.1. DO NOT EDIT.

package mocks

import (
	modules "mini-project/businesses/modules"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Create provides a mock function with given fields: moduleDomain
func (_m *Repository) Create(moduleDomain *modules.Domain) modules.Domain {
	ret := _m.Called(moduleDomain)

	var r0 modules.Domain
	if rf, ok := ret.Get(0).(func(*modules.Domain) modules.Domain); ok {
		r0 = rf(moduleDomain)
	} else {
		r0 = ret.Get(0).(modules.Domain)
	}

	return r0
}

// Delete provides a mock function with given fields: id
func (_m *Repository) Delete(id string) bool {
	ret := _m.Called(id)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// GetByID provides a mock function with given fields: id
func (_m *Repository) GetByID(id string) modules.Domain {
	ret := _m.Called(id)

	var r0 modules.Domain
	if rf, ok := ret.Get(0).(func(string) modules.Domain); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(modules.Domain)
	}

	return r0
}

// GetModules provides a mock function with given fields:
func (_m *Repository) GetModules() []modules.Domain {
	ret := _m.Called()

	var r0 []modules.Domain
	if rf, ok := ret.Get(0).(func() []modules.Domain); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]modules.Domain)
		}
	}

	return r0
}

// Update provides a mock function with given fields: id, blogDomain
func (_m *Repository) Update(id string, blogDomain *modules.Domain) modules.Domain {
	ret := _m.Called(id, blogDomain)

	var r0 modules.Domain
	if rf, ok := ret.Get(0).(func(string, *modules.Domain) modules.Domain); ok {
		r0 = rf(id, blogDomain)
	} else {
		r0 = ret.Get(0).(modules.Domain)
	}

	return r0
}

type mockConstructorTestingTNewRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepository(t mockConstructorTestingTNewRepository) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
