# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Deploy to Amazon EC2 

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout
      - name: use docker compose
      - run: docker-compose -f docker-compose.yml up
      